<div>
    @livewire('component.chetak-grid',
    [
    'headings' => [
    [
    'id' => 1,
    'label' => 'Text',
    'field' => 'text',
    'field_type' => 'text',
    'filter' => true,
    'editable' => true,
    ],
    [
    'id' => 2,
    'label' => 'url',
    'field' => 'url',
    'field_type' => 'text',
    'filter' => true,
    'editable' => true,
    ],
    [
    'id' => 3,
    'label' => 'icon',
    'field' => 'icon',
    'field_type' => 'text',
    'filter' => true,
    'editable' => true,
    ],
    [
    'id' => 4,
    'label' => 'label',
    'field' => 'label',
    'field_type' => 'text',
    'filter' => true,
    'editable' => true,
    ],
    [
    'id' => 5,
    'label' => 'label_color',
    'field' => 'label_color',
    'field_type' => 'text',
    'filter' => true,
    'editable' => true,
    ],
    [
    'id' => 6,
    'label' => 'order_by',
    'field' => 'order_by',
    'field_type' => 'text',
    'filter' => true,
    'editable' => true,
    ],
    ],
    'table'=>'menus',
    'where_con'=>null,
    'per_page_items' => 30,
    'inline_edit' => true,
    'deletable' => true,
    'editable' => true,
    'addable' => true,
    'viewable' => true,
    'exportable' => true,
    'raw_query'=>null,
    ],
    key('chetak-grid'.now()))
</div>